### ISSUE TITLE
Can that be integrated with W3ID ?

### ISSUE THREAD

**Issue by ameagol** [IBM/Ionic-MFP-App#12]
Hi Team, 

Is it possible to integrate it with W3ID ?
thank you

**Comment by shivahr** [comment]
Hi @ameagol we have another IBM code pattern in making https://github.com/IBM/MFP-Auth-LDAP that shows how IBM Mobile Foundation can be used for user authentication against on-prem LDAP server as well as social login such as Google/Facebook login.

If the above requirement is still there, then kindly follow up on that github repo.
