### ISSUE TITLE
step 7.3 target **Already Is** Android API 23

### ISSUE THREAD

**Issue by scottdangelo** [IBM/Ionic-MFP-App#4]
Just FYI, the instructions in step 7.3 state that you can change the Android API to level 23 in config.xml, but it already is:
```
    <preference name="android-targetSdkVersion" value="23" />
```

This is good, since not many phones will support API 26. But the README should probably be changed, since it might confuse the  user.

**Comment by shivahr** [comment]
https://github.com/IBM/Ionic-MFP-App/pull/11 closes this.
