### ISSUE TITLE
step 7.4 fails due to no ENV variables

### ISSUE THREAD

**Issue by scottdangelo** [IBM/Ionic-MFP-App#5]
The build fails in step 7.4:
`$ ionic cordova build android`
This is because the ENV variables aren't set.
See [This Code Pattern](https://github.com/IBM/watson-vehicle-damage-analyzer#6-install-dependencies-to-build-the-mobile-application)
for instructions (that you can just copy and paste to this readme) for setting:
 JAVA_HOME
ANDROID_HOME
ANDROID_SDK_HOME

After setting these, the app builds properly without error.

**Comment by shivahr** [comment]
After https://github.com/IBM/Ionic-MFP-App/pull/11, Readme.md in master branch now contains instructions to update ANDROID_HOME and JAVA_HOME environment variables. This should suffice to fix the cordova build problem seen in Step 7.5. @scottdangelo Can you please verify this once on your machine?

**Comment by scottdangelo** [comment]
LGTM
